import Head from "next/head";

import { Code, CopyRight, LinkCard, Logo } from "@norriswu/ui";

export default function Home() {
  const linkCards = [
    {
      href: "https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
      title: "Docs",
      description: "Find in-depth information about Next.js features and API.",
    },
    {
      href: "https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
      title: "Learn",
      description: "Learn about Next.js in an interactive course with quizzes!",
    },
    {
      href: "https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
      title: "Templates",
      description: "Discover and deploy boilerplate example Next.js projects.",
    },
    {
      href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
      title: "Deploy",
      description:
        "Instantly deploy your Next.js site to a shareable URL with Vercel.",
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-[100vh] flex-col items-center justify-between p-24">
        <div className="z-[2] flex w-full max-w-[var(--max-width)] items-center justify-between font-mono text-[0.85rem] mobile:text-[0.8rem]">
          <p className="relative m-0 rounded-[var(--border-radius)] border-[1px] border-solid border-[rgba(var(--callout-border-rgb),0.3)] bg-[rgba(var(--callout-rgb),0.5)] p-4">
            Get started by editing&nbsp;
            <Code>src/pages/index.tsx</Code>
          </p>

          <CopyRight />
        </div>

        <Logo />

        <div className="grid w-[var(--max-width)] max-w-full mobile:grid-cols-mobile tablet:grid-cols-tablet desktop:grid-cols-desktop">
          {linkCards.map((linkCard) => (
            <LinkCard key={linkCard.title} {...linkCard} />
          ))}
        </div>
      </main>
    </>
  );
}
